### ISSUE TITLE
problem with creating circular images

### ISSUE THREAD

**Issue by vtcloud** [dullemond/radmc3d-2.0#21]
Hi,

I'm trying out your software, downloaded as zip file from the git repository on June 15, 2022, and I stumbled over a bug when executing the run_spher1d_1 example. When executing the plot_session.py file, I'm getting an error message back:

Traceback (most recent call last):
  File "RADMC-3D/radmc-3d/radmc3d-2.0/examples/run_spher1d_1/plot_session.py", line 99, in <module>
    imcirc = readcircimage()
  File "anaconda3/envs/py39/lib/python3.9/site-packages/radmc3dPy/image.py", line 2185, in readcircimage
    dum.readImage(filename=filename, old=old)
  File "anaconda3/envs/py39/lib/python3.9/site-packages/radmc3dPy/image.py", line 2167, in readImage
    self.imageJyppix[:, :, ipol, inu] = self.image[:, :, ipol, inu] * conv
ValueError: could not broadcast input array from shape (111,1) into shape (110,1)

Digging deeper, aka isolating the routine that reads the image data and executing it outside of its package, I'm getting the following:

print(nr, nphi, nfreq, ri.shape, rc.shape, phii.shape, phic.shape, freq.shape, wav.shape, image.shape)

110 1 1 (112,) (111,) (2,) (1,) (1,) (1,) (111, 1, 1, 1)

It looks like that the problem is in creating the data since the ri and rc array in the data file already have different sizes (112 and 111 respectively) and their sizes differs from what it should be (=> 110). Hence the error message above.
At least that is how it looks to me... 
I am working on a Mac with Big Sur, using gfortran 11.3.0 and python 3.9.
Thanks.

**Comment by dullemond** [comment]
This Python package is something that was written by someone else (author = Attila Juhasz, who left science). It seems indeed a bug, but I don't have time to fix it myself (at least not now). Would you be willing to try to fix it in the image.py file?

**Comment by vtcloud** [comment]
Sorry for the late response and the confusion.
I did some further checking and found that the python code coming with radmc3d-2.0 is actually working. The most likely culprit was an older version of the radmc3dPy package. Unfortunately, when I installed the version from this repository, I lost the traceback to what version was installed. The only part known is that the version came from Juhasz's repository, downloaded separately.
